[manifest]
version = "1.0.0"
dump_lua = true
priority = -9

#
# context.modify_hand_chips START
#

# Calculate hand score just once
# Allow game objects to modify final score given by played hand
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, after = true})'''
position = "at"
payload = '''
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, after = true, hand_chips = final_hand_chips})'''
match_indent = true
